version: "3.8"

services:
  wordpress:
    image: bluegrassdigital/wordpress-azure-sync:8.4-dev-latest
    ports:
      - "8080:80"
    environment:
      - HOST_DOMAIN=localhost:8080
      - MYSQLCONNSTR_defaultConnection=Data Source=db;Database=wordpress;User Id=wordpress;Password=wordpress
    volumes:
      - ./src:/home/site/wwwroot
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
