version: "3.8"

services:
  wordpress:
    image: bluegrassdigital/wordpress-azure-sync:8.4-dev-latest
    ports:
      - "8080:80"
    environment:
      - APP_ENV=development
      - HOST_DOMAIN=localhost:8080
      - MYSQLCONNSTR_defaultConnection=Data Source=db;Database=wordpress;User Id=wordpress;Password=wordpress
      - WORDPRESS_CONFIG_EXTRA=if(!defined('USE_PCONNECT')){define('USE_PCONNECT',false);} if(!defined('DB_HOST')){define('DB_HOST','db:3306');} if(defined('MYSQL_CLIENT_FLAGS')){define('MYSQL_CLIENT_FLAGS',0);} if(defined('MYSQL_SSL_CA')){define('MYSQL_SSL_CA',null);} if(!defined('WP_DEBUG')){define('WP_DEBUG',false);} if(!defined('WP_DEBUG_DISPLAY')){define('WP_DEBUG_DISPLAY',false);} if(!defined('WP_DEBUG_LOG')){define('WP_DEBUG_LOG',true);}
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
      - DOCKER_SYNC_ENABLED=1
      - WAZM_AUTO_ACTIVATE=1
    volumes:
      - ./src:/home/site/wwwroot
      - ../wordpress-plugin/wordpress-azure-monitor:/home/site/wwwroot/wp-content/plugins/wordpress-azure-monitor
      - ../wordpress-plugin/wordpress-azure-monitor:/homelive/site/wwwroot/wp-content/plugins/wordpress-azure-monitor
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
