name: Build and Push Docker Images

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"   # Weekly rebuild to pick up PHP/OS patches

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.3", "8.4"]
    env:
      REGISTRY: docker.io
      IMAGE_NAME: bluegrassdigital/wordpress-azure-sync
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (prod, multi-arch)
        id: build_prod
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ (github.ref_type == 'tag' || github.event_name == 'schedule') && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          cache-from: type=gha,scope=${{ matrix.php_version }}-prod
          cache-to: type=gha,mode=max,scope=${{ matrix.php_version }}-prod
          provenance: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.php_version }}-latest
            ${{ (github.ref_type == 'tag' || github.event_name == 'schedule') && format('{0}:{1}-stable', env.IMAGE_NAME, matrix.php_version) || '' }}
            ${{ env.IMAGE_NAME }}:${{ matrix.php_version }}-build-${{ github.sha }}

      - name: Build and push (dev, multi-arch)
        id: build_dev
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: dev
          platforms: ${{ (github.ref_type == 'tag' || github.event_name == 'schedule') && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          cache-from: type=gha,scope=${{ matrix.php_version }}-dev
          cache-to: type=gha,mode=max,scope=${{ matrix.php_version }}-dev
          provenance: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.php_version }}-dev-latest
            ${{ (github.ref_type == 'tag' || github.event_name == 'schedule') && format('{0}:{1}-dev-stable', env.IMAGE_NAME, matrix.php_version) || '' }}
            ${{ env.IMAGE_NAME }}:${{ matrix.php_version }}-dev-build-${{ github.sha }}

      - name: Resolve full PHP version from prod image
        id: phpver_prod
        env:
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          FULL=$(docker run --rm $IMAGE:${{ matrix.php_version }}-build-${{ github.sha }} php -r 'echo PHP_VERSION;')
          echo "full=$FULL" >> $GITHUB_OUTPUT

      - name: Resolve full PHP version from dev image
        id: phpver_dev
        env:
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          FULL=$(docker run --rm $IMAGE:${{ matrix.php_version }}-dev-build-${{ github.sha }} php -r 'echo PHP_VERSION;')
          echo "full=$FULL" >> $GITHUB_OUTPUT

      - name: Add tag with full PHP version (prod, multi-arch)
        env:
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then \
            docker buildx imagetools create --tag $IMAGE:${{ steps.phpver_prod.outputs.full }} $IMAGE:${{ matrix.php_version }}-build-${{ github.sha }}; \
          fi

      - name: Add tag with full PHP version (dev, multi-arch)
        env:
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then \
            docker buildx imagetools create --tag $IMAGE:${{ steps.phpver_dev.outputs.full }}-dev $IMAGE:${{ matrix.php_version }}-dev-build-${{ github.sha }}; \
          fi

      - name: Trivy scan (prod image - table)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ matrix.php_version }}-build-${{ github.sha }}
          vuln-type: 'os,library'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'table'
          output: trivy-prod.txt
          exit-code: '0'

      - name: Trivy Summary (prod)
        run: |
          echo "### Trivy scan (prod) for PHP ${{ matrix.php_version }}" >> $GITHUB_STEP_SUMMARY
          cat trivy-prod.txt >> $GITHUB_STEP_SUMMARY

      - name: Trivy scan (dev image - table)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ matrix.php_version }}-dev-build-${{ github.sha }}
          vuln-type: 'os,library'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'table'
          output: trivy-dev.txt
          exit-code: '0'

      - name: Trivy Summary (dev)
        run: |
          echo "### Trivy scan (dev) for PHP ${{ matrix.php_version }}" >> $GITHUB_STEP_SUMMARY
          cat trivy-dev.txt >> $GITHUB_STEP_SUMMARY

      - name: Trivy SARIF (prod image)
        if: ${{ github.ref_type == 'tag' || github.event_name == 'schedule' }}
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ matrix.php_version }}-build-${{ github.sha }}
          vuln-type: 'os,library'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: trivy-prod.sarif
          exit-code: '0'

      - name: Upload SARIF (prod)
        if: ${{ github.ref_type == 'tag' || github.event_name == 'schedule' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-prod.sarif
          category: trivy-prod-${{ matrix.php_version }}

      - name: Trivy SARIF (dev image)
        if: ${{ github.ref_type == 'tag' || github.event_name == 'schedule' }}
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ matrix.php_version }}-dev-build-${{ github.sha }}
          vuln-type: 'os,library'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: trivy-dev.sarif
          exit-code: '0'

      - name: Upload SARIF (dev)
        if: ${{ github.ref_type == 'tag' || github.event_name == 'schedule' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-dev.sarif
          category: trivy-dev-${{ matrix.php_version }}
